version: "3.1"
services:
    db:
        image: mysql
        expose: 
            - "3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    apache1:
        build: .
        expose: 
            - "80"
        volumes:
            - ./www/apache1:/var/www/html
        links:
            - db
        networks:
            - default
            - web
        labels:
            - traefik.http.routers.NAME.rule=Host(`yourdomainaccess`)
            - traefik.http.routers.NAME.tls=true
            - traefik.http.routers.NAME.tls.certresolver=lets-encrypt
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        expose:
            - 80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
volumes:
    persistent:

networks:
  web:
   external: true
